# DNA_2CNN_2FC_Multi config params

lr: [0.001, 0.0005, 0.0001]
        
module__num_filters1: [32,64,128,256]
module__num_filters2: [32,64,128]

module__kernel_size1: [8,12,16,24]
module__kernel_size2: [8,12,16,24]

module__conv_pool_size1: [1,3,]
module__fc_node_num1: [25,50,100,250]
module__fc_node_num2: [25,50,100,250]

module__dropout1: [0.0,0.1,0.2,0.4]
module__dropout2: [0.0,0.1,0.2,0.4]

optimizer: [SGD,AdamW,RMSprop]