# DNA_2CNN/DNA_2CNN_Multi config params

lr: [0.001, 0.0005, 0.0001]
        
module__num_filters1: [16,32,64]
module__num_filters2: [16,32,64]

module__kernel_size1: [6,8,12,16]
module__kernel_size2: [6,8,12,16]

module__conv_pool_size1: [1,3,6]
module__fc_node_num1: [10,25,50]

module__dropout1: [0.1,0.2,0.5]
module__dropout2: [0.1,0.2,0.5]

optimizer: [SGD,AdamW,RMSprop]